FROM ubuntu:24.04

ENV TZ=Europe/Warsaw
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get -y dist-upgrade
RUN apt-get -y install openjdk-17-jdk

USER ubuntu

RUN mkdir -p /home/ubuntu/.gradle
RUN mkdir -p /home/ubuntu/app
WORKDIR /home/ubuntu/app

ENTRYPOINT ["/usr/bin/bash", "entrypoint.sh"]
