FROM eclipse-temurin:17 AS build
RUN mkdir /app
WORKDIR /app
COPY build.gradle.kts settings.gradle.kts gradlew ./
COPY ./gradle ./gradle
RUN ./gradlew dependencies
COPY src ./src
RUN ./gradlew bootJar
# CMD ["/bin/sh"]

FROM ubuntu/jre:17-24.04_stable
WORKDIR /app
COPY --from=build /app/build/libs/app.jar ./app.jar
CMD ["exec", "java", "-jar", "/app/app.jar"]